export const GET_ORDERS = 'GET_ORDERS'
export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST'
export const GET_ORDERS_FAILURE = 'GET_ORDERS_FAILURE'
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS'